config/routes.rb
Demo::Application.routes.draw do
  
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy', as: 'signout'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
    
  
  resources :articles do
    collection do
      get 'list'
      get 'remove'
    end 
    resources :comments do
      collection do
        get 'remove'
      end  
    end    
  end

  resources :tags
  resources :products
  resources :categories do
    collection do
      get 'category_products' => 'categories#category_products'
    end  
  end  

    

 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user
    if user.role == "admin"
      can :manage, :all

    else
      can :read, :all
      can :manage, Comment
    end
    if user.role == "author"
      can :manage, Comment 
      can :create, Article
      can :update, Article do |article|
        article.try(:user) == user
      end
    end
    if user.role == "owner"
      can :create, Product
    end  
  end  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation 
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :comments, :dependent => :destroy 
  belongs_to :user
  scope :unreleased, where(:created_at => nil)
  attr_accessible :user_id, :title, :text, :image, :remote_image_url, :tag_list
  mount_uploader :image, ImageUploader

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  include PgSearch
  pg_search_scope :search, :against => [:title, :text, :id, :user_id] 
 
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products		
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  attr_accessible :user_id, :article_id, :commenter, :body
 
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :name, :description, :category_id	
    searchable do
      text :name, :boost => 2
      text :description
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  attr_accessible :name
  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :products
  has_many :articles
  has_many :comments, :dependent => :destroy 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  ROLES = %w[admin moderator author owner]
  accepts_nested_attributes_for :articles 
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :products

  attr_accessible :username, :email, :password, :password_confirmation, :role, :avatar, :remember_me, :date_of_birth, :gender, :provider, :uid, :oauth_token, :oauth_expires_at, :name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def self.from_omniauth(auth, signed_in_resource=nil)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
       
        user = User.create(username:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end 


  def role?(role)
    roles.include? role.to_s
  end  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource  only: [:new, :create, :update, :remove] 
  helper_method :sort_column, :sort_direction 

  def index
    debugger
    if params[:search] 
      @articles = Article.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5) 
    else  
      @articles = Article.all.paginate(:page => params[:page], :per_page => 5) 
    end  
  end

  def new
  end
  
  def create 
    @user = current_user
    @article = @user.articles.build(:title => params[:article][:title],:text=> params[:article][:text], :image=> params[:article][:image], :tag_list => params[:article][:tag_list])
    @article.tags
    @article.save
      redirect_to @article
  end

  def show
    @article = Article.find(params[:id]) 
   #@comment = Comment.new(:article => @article)
  end
  
  def edit
    @article = Article.find(params[:id]) 
  end
  
  
  def update
    if current_user.role == "admin" 
      @article = @article.update_attributes(params.require(:article).permit(:tag_list, :title, :text, :image))
      flash[:notice] = "admin successfully updated article."
      redirect_to article_path
    elsif current_user.role == "author" && @article.user_id == current_user.id
      @article = @article.update_attributes(params.require(:article).permit(:tag_list, :title, :text, :image))
      flash[:notice] = "author successfully updated article."
      redirect_to article_path
    else
      flash[:notice] = "you don't have the permmision for article update"
      render 'edit'
    end    
  end

  def remove
    @article = Article.find(params[:format])
    @article.delete
    flash[:notice] = "article destroy successfully."
    redirect_to articles_path    
  end

  def list
    @articles = Article.all.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 5)   
  end 

  private  
  def sort_column  
    Article.column_names.include?(params[:sort]) ? params[:sort] : "title"  
  end   
    
  def sort_direction  
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
  end  


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil 
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_articles.html.erb
<table class="pretty">
  <thead class = "current">
    <tr>
        <th><%= sortable "id" %></th>  
        <th><%= sortable "title" %></th>  
        <th><%= sortable "text" %></th>
        <th><%= sortable "user_id" %></th>
        <th><%= sortable "image" %></th>
        <th><%= sortable "created_at", "Created_at" %></th> 
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= article.user_id %></td>
        <td><%= image_tag article.image_url(:thumb) rescue 0 %></td>
        <td><%= article.created_at %></td>  
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
    
  <% if params[:preview_button] %>
    <dl class="dl-horizontal">
      <dt><strong>Title</strong></dt>
      <dd><%= @article.title %></dd>
      <dt><strong>Text</strong></dt>
      <dd><%= @article.text %></dd>
      <dt><strong>Image</strong></dt>
      <dd><%= image_tag @article.image_url(:thumb) %></dd>
  <% end %>
  
  <div class="control-group">
    <%= f.label :tag_list, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'text_field' %>
    </div>
  </div>
   
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    
    <%= submit_tag 'Preview', :name => 'preview_button' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag articles_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%= render 'articles/search' %>
<div id="articles">
  <%= render 'articles/articles' %>
</div>

app/views/articles/index.js.erb
$("#articles").html("<%= escape_javascript(render("articles")) %>");

app/views/articles/list.html.erb
<%= render 'articles/search' %>
<div id="articles">
  <%= render 'articles/articles' %>
</div>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tag_name) %>:</strong></dt>
  <dd><%= @article.tag_list %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @article.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @article.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @article.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @article.image_url(:thumb) rescue 0 %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>   
<% if can? :update, @article %>                       
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
<% end %>
<% if can? :remove, @article %>
  <%= link_to 'Remove', remove_articles_path(@article),
            :confirm => 'Are you sure?', :method => :delete %>          
<% end %>              
</div>
<h3>Comments (<%= @article.comments.size %>)</h3>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% if can? :update, comment %>  
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_comment_path(@article, comment), :class => 'btn' %>
<% end %>

<% if can? :remove, comment %>              
  <%= link_to "Destroy", remove_article_comments_path(@article, comment), :method => :delete, :confirm => "Are you sure?" %> 

<% end %>              
  
<% end %>
<h2>Add a comment:</h2>
<%= render 'comments/form'%>