config/routes.rb
Demo::Application.routes.draw do
  
  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  get 'signout' => 'sessions#destroy', as: 'signout'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } 
    
  
  resources :articles do
    collection do
      get 'list'
      get 'remove'
    end 
    resources :comments do
      collection do
        get 'remove'
      end  
    end    
  end

  resources :tags
  resources :products
  resources :categories do
    collection do
      get 'category_products' => 'categories#category_products'
    end  
  end  

    

 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user
    if user.role == "admin"
      can :manage, :all

    else
      can :read, :all
      can :manage, Comment
    end
    if user.role == "author"
      can :manage, Comment 
      can :create, Article
      can :update, Article do |article|
        article.try(:user) == user
      end
    end
    if user.role == "owner"
      can :create, Product
    end  
  end  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation 
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :comments, :dependent => :destroy 
  belongs_to :user
  scope :unreleased, where(:created_at => nil)
  attr_accessible :user_id, :title, :text, :image, :remote_image_url, :tag_list
  mount_uploader :image, ImageUploader

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  include PgSearch
  pg_search_scope :search, :against => [:title, :text, :id, :user_id] 
 
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products		
  attr_accessible :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  attr_accessible :user_id, :article_id, :commenter, :body
 
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :name, :description, :category_id	
    searchable do
      text :name, :boost => 2
      text :description
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
  attr_accessible :name
  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :products
  has_many :articles
  has_many :comments, :dependent => :destroy 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable
  ROLES = %w[admin moderator author owner]
  accepts_nested_attributes_for :articles 
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :products

  attr_accessible :username, :email, :password, :password_confirmation, :role, :avatar, :remember_me, :date_of_birth, :gender, :provider, :uid, :oauth_token, :oauth_expires_at, :name
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def self.from_omniauth(auth, signed_in_resource=nil)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
       
        user = User.create(username:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end 


  def role?(role)
    roles.include? role.to_s
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize  
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil 
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="http://localhost:3000/articles">Blog</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
              <li>Signed in as <%= current_user.username %></li>
              <li><%= link_to "Create Article", new_article_path %></li>
              <li><%= link_to "Create Product", new_product_path %></li>
              <li><%= link_to "Create Category", new_category_path %></li>
              <li><%= link_to "Products", products_path %></li>
              <li><%= link_to "Categories", categories_path %></li>
              <li><%= link_to "CurrentUserArticle", list_articles_path %></li>
              <li><%= link_to "UpdateProfile", edit_user_registration_path %></li>
              <li><%= link_to "SignOut", destroy_user_session_path, :method => 'delete' %></li>
            <% else %>
              <li><%= link_to "SignUp", new_user_registration_path %></li>
              <li><%= link_to "SignIn", new_user_session_path %></li>
              <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li> 
              
              <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>

            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  
  
  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        This is my first blog application which i can develop via devise ,cancan and active admin gem.
      </div>
    </div>  
  </div>  


</body>
</html>